add gr8conf
max-mapper/hexbin pull request #112
Opened 2016-08-12 13:51 UTC by sbglasius

GR8Conf is an All Things Groovy conference running in Europe, US and India

2016-09-02 18:34 UTC, flyswatter commented
`.ai` isn't a web format, could you re-submit as an `.svg`?

2016-09-21 06:10 UTC, sbglasius commented
Updated to `.svg` vector

2016-09-30 21:58 UTC, danfinlay requested changes

2016-09-30 21:58 UTC, flyswatter commented on meta/gr8conf.json
> +  "vector": "http://hexb.in/vector/gr8conf.ai",
Need to update this reference to point to the new `.svg` file.

2016-09-30 22:01 UTC, flyswatter commented on meta/gr8conf.json
> +  "description": "GR8Conf - The 'All Things Groovy' conference",
Trailing comma is invalid JSON, will fail our build, too.  Sorry!

2017-07-16 23:57 UTC, merged