Add Clerky
max-mapper/hexbin pull request #127
Opened 2016-10-13 00:19 UTC by akshayrawat

2016-10-13 10:58 UTC, derhuerst commented
Is there an SVG version of this really simple logo? (:

2016-10-13 16:53 UTC, akshayrawat commented
@derhuerst Its already in this PR, right? Did I miss something?

2016-10-13 18:45 UTC, derhuerst commented
Sorry, I missed something. :flushed:

2017-11-07 06:30 UTC, Ruxton requested changes

2017-11-07 06:30 UTC, Ruxton commented on meta/clerky.json
> +  "description": "https://www.clerky.com",
Please provide a more useful description

2017-11-07 06:30 UTC, Ruxton commented on meta/clerky.json
> +  "license": "None",
Please provide an accurate license

2017-12-31 19:13 UTC, closed without merging