add osig (https://osf.io/2dfhz/)
max-mapper/hexbin pull request #144
Opened 2017-03-14 17:17 UTC by benmarwick

![osig](https://cloud.githubusercontent.com/assets/1262179/23913198/692a6616-089f-11e7-89d4-0c357d92a16c.png)

thanks!

2017-11-07 06:09 UTC, Ruxton requested changes

2017-11-07 06:09 UTC, Ruxton commented on meta/osig.json
> +  "order_online_url": ""
Please remove the order_online_url if you don't have a value for it.

2018-06-23 07:18 UTC, pkq approved these changes
Thanks @benmarwick !

2018-06-23 07:18 UTC, merged

2018-06-23 07:30 UTC, pkq commented
@benmarwick – It looks like the `.png` uses a transparent background. Is that intentional?