add ModernDive
max-mapper/hexbin pull request #165
Opened 2017-09-13 20:13 UTC by rudeboybert

![moderndive](https://user-images.githubusercontent.com/4574203/30398452-638ff70e-989e-11e7-8424-6eb70f31e9e8.png)

2017-11-07 05:35 UTC, Ruxton commented
Please update your description to something useful that describes ModernDive.

2017-11-11 14:34 UTC, rudeboybert commented
Hello, 
- updated the `description`
- `order_online_url` is left blank. I contacted stickermule to ask if they could add our design, to which they replied: *Please note that we are re-evaluating the marketplace's future viability and, consequently, not accepting new designs. :(*

2017-11-14 04:13 UTC, Ruxton approved these changes

2017-11-14 04:13 UTC, Ruxton commented on meta/moderndive.json
> +  "order_online_url": ""
Remove the order_online_url if it is going to be empty.

2017-11-14 04:13 UTC, Ruxton requested changes
Please remove the order_online_url

2017-11-14 11:41 UTC, rudeboybert commented
Done. thanks

2018-02-21 22:47 UTC, rudeboybert commented
Hi @Ruxton I removed `order_online_url` a while back. Are there any other problems?

2018-06-06 18:10 UTC, pkq commented
Looks good @rudeboybert! cc @ismayc

2018-06-06 18:10 UTC, merged