Adding RaukR. Advanced R for Bioinformatics Summer School hex.
max-mapper/hexbin pull request #190
Opened 2018-04-17 11:34 UTC by quiestrho

Added hex for RaukR. Advanced R for Bioinformatics Summer School. 
![raukr-2018](https://user-images.githubusercontent.com/4972207/38867321-fe6be41e-4243-11e8-96b1-fe7487e4f82f.png)

2018-06-06 19:35 UTC, pkq requested changes
@quiestrho The `order_online_url` is intended to be the URL where copies of the sticker can be purchased, not a repository link. Please change that, or remove the line entirely. Thanks!

2018-06-20 08:19 UTC, quiestrho commented
Done. Thanx.

2018-06-23 06:59 UTC, pkq approved these changes

2018-06-23 06:59 UTC, merged

2018-06-23 07:00 UTC, pkq commented
Thanks for contributing!