add parEBEN
max-mapper/hexbin pull request #221
Opened 2019-01-24 16:15 UTC by colbyford

Added assets for the parEBEN package in R.

2019-04-24 01:05 UTC, hexagontruth requested changes
Hi the text in your SVG is sort of off. Can you make it match the raster version?

2019-04-24 04:04 UTC, colbyford commented
Hi, I've converted the text to shapes. (I think this was due to a missing font...)
Thanks

2019-04-25 01:43 UTC, hexagontruth approved these changes

2019-04-25 01:44 UTC, hexagrahamaton commented
This is fine, but I can't help but notice the raster image is not particularly well anti-aliased. Is this intentional? Feel free to submit another PR with an anti-aliased version if you want.

2019-04-25 01:44 UTC, merged